# Generated by Django 5.0 on 2026-03-09 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('speed', models.IntegerField(default=0)),
                ('duplex', models.CharField(blank=True, max_length=20)),
                ('vlan', models.IntegerField(default=1)),
                ('poe_power', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('ios_version', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('snmp_community', models.CharField(default='public', max_length=50)),
                ('total_poe_power', models.FloatField(default=0)),
                ('cpu_usage', models.FloatField(default=0)),
                ('memory_usage', models.FloatField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crc_errors', models.IntegerField(default=0)),
                ('input_errors', models.IntegerField(default=0)),
                ('output_drops', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interface')),
            ],
        ),
        migrations.CreateModel(
            name='MACTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=20)),
                ('interface', models.CharField(max_length=50)),
                ('vlan', models.IntegerField()),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.switch')),
            ],
        ),
        migrations.AddField(
            model_name='interface',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.switch'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.switch')),
            ],
        ),
        migrations.CreateModel(
            name='ARPTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=20)),
                ('vlan', models.IntegerField()),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.switch')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.switch')),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_octets', models.BigIntegerField(default=0)),
                ('out_octets', models.BigIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interface')),
            ],
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.switch')),
            ],
        ),
    ]
