# Generated by Django 5.0 on 2026-04-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='location',
            field=models.CharField(blank=True, help_text='مثل: مبنى A, الطابق 2, غرفة السيرفرات', max_length=100, null=True),
        ),
    ]
