# Generated by Django 5.0 on 2026-04-22 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_location_alter_switch_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortFlapEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_status', models.CharField(max_length=10)),
                ('to_status', models.CharField(max_length=10)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interface')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_flap_events', to='core.switch')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['switch', 'interface', '-timestamp'], name='core_portfl_switch__368860_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortFlapSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('flap_count', models.IntegerField(default=0)),
                ('total_down_time', models.IntegerField(default=0)),
                ('last_flap_time', models.DateTimeField(blank=True, null=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.interface')),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_flap_summaries', to='core.switch')),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('switch', 'interface', 'period_start', 'period_end')},
            },
        ),
    ]
