# Generated by Django 5.0 on 2026-04-24 00:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_portflapevent_portflapsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portflapevent',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.switch'),
        ),
        migrations.AlterField(
            model_name='portflapsummary',
            name='switch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.switch'),
        ),
        migrations.CreateModel(
            name='PortEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('link_down', 'Link Down'), ('link_up', 'Link Up'), ('flap', 'Port Flap (down+up)'), ('crc_spike', 'CRC Error Spike'), ('drop_spike', 'Drop Spike'), ('error_clear', 'Errors Cleared'), ('traffic_surge', 'Traffic Surge'), ('traffic_drop', 'Traffic Drop'), ('speed_change', 'Speed Change'), ('poe_fault', 'PoE Fault'), ('poe_recovered', 'PoE Recovered'), ('poe_overload', 'PoE Overload'), ('vlan_change', 'VLAN Change'), ('vlan_mismatch', 'VLAN Mismatch'), ('stp_blocking', 'STP Blocking'), ('stp_forwarding', 'STP Forwarding'), ('admin_down', 'Admin Shutdown'), ('admin_up', 'Admin Enabled')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info'), ('ok', 'OK / Recovered')], default='info', max_length=16)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('old_value', models.CharField(blank=True, max_length=128)),
                ('new_value', models.CharField(blank=True, max_length=128)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('alerted', models.BooleanField(default=False)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_events', to='core.switch')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['switch', 'port_name', 'occurred_at'], name='core_portev_switch__05e8d9_idx'), models.Index(fields=['switch', 'event_type', 'occurred_at'], name='core_portev_switch__12cf1b_idx'), models.Index(fields=['severity', 'occurred_at'], name='core_portev_severit_7016ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='PortFlapCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(max_length=64)),
                ('window_start', models.DateTimeField(db_index=True)),
                ('window_end', models.DateTimeField()),
                ('flap_count', models.IntegerField(default=0)),
                ('down_count', models.IntegerField(default=0)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flap_counters', to='core.switch')),
            ],
            options={
                'ordering': ['-window_start'],
                'unique_together': {('switch', 'port_name', 'window_start')},
            },
        ),
        migrations.CreateModel(
            name='PortSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_name', models.CharField(db_index=True, max_length=64)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('oper_status', models.CharField(max_length=16)),
                ('admin_status', models.CharField(max_length=16)),
                ('speed_bps', models.BigIntegerField(default=0)),
                ('in_octets', models.BigIntegerField(default=0)),
                ('out_octets', models.BigIntegerField(default=0)),
                ('in_errors', models.BigIntegerField(default=0)),
                ('out_errors', models.BigIntegerField(default=0)),
                ('in_discards', models.BigIntegerField(default=0)),
                ('out_discards', models.BigIntegerField(default=0)),
                ('poe_status', models.CharField(blank=True, max_length=16)),
                ('poe_power_mw', models.IntegerField(default=0)),
                ('vlan_id', models.IntegerField(blank=True, null=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_snapshots', to='core.switch')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['switch', 'port_name', 'recorded_at'], name='core_portsn_switch__ba37f3_idx')],
            },
        ),
    ]
